### ISSUE TITLE
import方法有误

### ISSUE THREAD

**Issue by zangxx66** [museui/muse-ui-carbon-theme#1]
应该是
`import { theme } from 'muse-ui'`
`import { carbon, createTheme } from 'muse-ui-carbon-theme/src'`
而不是
`import { theme } from 'muse-ui'`
`import { carbon, createTheme } from '../src';`吧
不然会报错无法识别模块
在[官方文档](https://muse-ui.org/#/zh-CN/theme)的例子中，应该也是
`import {theme} from 'muse-ui'`
而不是
`import theme from 'muse-ui/lib/theme'`
这样写好像是会导致扩展主题报错

**Comment by myronliu347** [comment]
import { carbon, createTheme } from 'muse-ui-carbon-theme'
